### ISSUE TITLE
es6 Minifier compatability Issues

### ISSUE THREAD

**Issue by rhysldavis** [pbakondy/android-device-list#1]
Hey mate,

Using your android-device-list in a Meteor project.  Recently upgraded from version 1.0.70 to latest and our project started breaking in production build.  Following error:

While minifying app code:

```
eval at <anonymous> (/-/-/.meteor/packages/standard-minifier-js/.1.2.1.3ev2z0++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
   <anonymous>:1545:18: SyntaxError: Unexpected token: operator (>)
at new JS_Parse_Error (eval at <anonymous>
```

Same is not true of the ios-device-list.

**Comment by pbakondy** [comment]
Could you give me an exact line number for this error, mate?

**Comment by werdna11** [comment]
I have no idea.Thanks


________________________________
