### ISSUE TITLE
Needs a new build

### ISSUE THREAD

**Issue by cowai** [pbakondy/android-device-list#2]
I looked up: "AGS-L09".
It returned a chinese name: "\xe8\x8d\xa3\xe8\x80\x80\xe7\x95\x85\xe7\x8e\xa9\xe5\xb9\xb3\xe6\x9d\xbf2 9.6"

When I run build.js and lookup again I get "HUAWEI MediaPad T3 10".

Maybe it would be desirable to have it auto update the devices.json after some time?

**Comment by pbakondy** [comment]
Solved
