### ISSUE TITLE
Build error for Angular project

### ISSUE THREAD

**Issue by trevorsmiley** [pbakondy/android-device-list#3]
`#!/usr/bin/env node`
at the top of **index.js** creates an issue when building for an Angular project.

> ERROR in ./node_modules/android-device-list/index.js 1:0
Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
> #!/usr/bin/env node
| 
| 'use strict';

Removing it allows it to work

**Comment by MartianH** [comment]
Same problem for react (16.6.x) with `create-react-app`.

**Comment by pbakondy** [comment]
Solved
