### ISSUE TITLE
Can you upload the full CSV? My use case requires some of the other data.

### ISSUE THREAD

**Issue by Pilfer** [pbakondy/android-device-list#4]
The data source page listed in the readme states the following:

```
On the CSV file, devices are ordered alphabetically (A-Z) by manufacturer name and listed in the following format:

Retail brand, model name, model code, RAM (total memory), form factor, system on chip, screen sizes, screen densities, ABIs, Android SDK versions, OpenGL ES Version.
```

Is there any way you could either dump the full CSV with the hardware information, or add it to this repo? Would be super helpful - thanks!

**Comment by pbakondy** [comment]
You can download the CVS file yourself from the Google site.

**Comment by Pilfer** [comment]
@pbakondy They require you to have an APK in the play store as far as I can tell, so I was hoping to bypass this restriction. Do you know of another area that will allow me to download the aforementioned CSV file without having an APK uploaded?

Thanks!

**Comment by Pilfer** [comment]
Just following up, I was able to successfully download the CSV by uploading a "Hello World" bundle - ezpz. Thanks for the assistance!
