### ISSUE TITLE
There need to change hex to string

### ISSUE THREAD

**Issue by qin-young** [pbakondy/android-device-list#5]
![image](https://user-images.githubusercontent.com/18627148/69539476-87d0ce00-0fbf-11ea-9c62-2fd4cf17bbc4.png)

**Comment by qin-young** [comment]
For me，below is work
![image](https://user-images.githubusercontent.com/18627148/69539773-23fad500-0fc0-11ea-94c1-b83ffc69f04e.png)

**Comment by pbakondy** [comment]
Done
